package forms;


import Class.Sobrado;
import dB.ConectaBanco;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Maxximus
 */
public class FormularioObrasSalao extends javax.swing.JFrame {

    
    ConectaBanco conecta = new ConectaBanco();
    
    Sobrado novo;
    
    public FormularioObrasSalao() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preenchCampos = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        nomeObraInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dataTerminoInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dataInicioInput = new javax.swing.JTextField();
        labelTipoSobrado = new javax.swing.JLabel();
        labelLaje = new javax.swing.JLabel();
        labelReboco = new javax.swing.JLabel();
        tipoDoSobradoInput = new javax.swing.JComboBox();
        lajeInput = new javax.swing.JComboBox();
        rebocoInput = new javax.swing.JComboBox();
        labelObraMetros = new javax.swing.JLabel();
        metroObraInput = new javax.swing.JTextField();
        labelAlvenariaMetros = new javax.swing.JLabel();
        alvenariaMetroInput = new javax.swing.JTextField();
        boxUmavezInput = new javax.swing.JComboBox();
        labelVigaBaldrame = new javax.swing.JLabel();
        VigaBaldrameInput = new javax.swing.JTextField();
        labelCobertura = new javax.swing.JLabel();
        CoberturaMLInput = new javax.swing.JTextField();
        labelPilares = new javax.swing.JLabel();
        pilaresMLInput = new javax.swing.JTextField();
        labelTijolo = new javax.swing.JLabel();
        tijoloTipoInput = new javax.swing.JComboBox();
        labelTipo = new javax.swing.JLabel();
        tipoMaterialInput = new javax.swing.JComboBox();
        labelEsquadria = new javax.swing.JLabel();
        esquadriaMetrosInput = new javax.swing.JTextField();
        labelContraPiso = new javax.swing.JLabel();
        contraPisoEmMetrosInput = new javax.swing.JTextField();
        labelBanheirosQtde = new javax.swing.JLabel();
        labelLavaboQtde = new javax.swing.JLabel();
        botaoSalvarObra = new javax.swing.JButton();
        botaoCancelarObra = new javax.swing.JButton();
        qtdBanheiroInput = new javax.swing.JComboBox();
        tipoLavabosInput = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        preenchCampos.setText("Preencha os campos abaixo");

        labelNome.setText("Nome:");

        nomeObraInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeObraInputActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de Inicio:");

        dataTerminoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTerminoInputActionPerformed(evt);
            }
        });

        jLabel4.setText("Data de Termino:");

        dataInicioInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataInicioInputActionPerformed(evt);
            }
        });

        labelTipoSobrado.setText("Tipo da Obra");

        labelLaje.setText("Laje?");

        labelReboco.setText("Reboco?");

        tipoDoSobradoInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Salão" }));
        tipoDoSobradoInput.setEnabled(false);
        tipoDoSobradoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDoSobradoInputActionPerformed(evt);
            }
        });

        lajeInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));

        rebocoInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));

        labelObraMetros.setText("Obra(em m²)");

        metroObraInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metroObraInputActionPerformed(evt);
            }
        });

        labelAlvenariaMetros.setText("Alvenaria(em m²)");

        alvenariaMetroInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alvenariaMetroInputActionPerformed(evt);
            }
        });

        boxUmavezInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Uma vez", "Meia Vez" }));

        labelVigaBaldrame.setText("Viga Baldrame(em m²)");

        labelCobertura.setText("Cobertura(em ML)");

        labelPilares.setText("Pilares(em ML)");

        labelTijolo.setText("Tijolo");

        tijoloTipoInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bloco de Concreto", "Tijolo Barro Cozido", "Tijo Furado - 8 Furos", "Tijolo Furado - 10 Furos", "Tijolo de Vidro" }));

        labelTipo.setText("Tipo");

        tipoMaterialInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ferro", "Madeira", "Aluminio" }));

        labelEsquadria.setText("Esquadria(em m²)");

        labelContraPiso.setText("ContraPiso (em m²)");

        labelBanheirosQtde.setText("Banheiros");

        labelLavaboQtde.setText("Lavabos");

        botaoSalvarObra.setText("Próximo");
        botaoSalvarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarObraActionPerformed(evt);
            }
        });

        botaoCancelarObra.setText("Cancelar");
        botaoCancelarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarObraActionPerformed(evt);
            }
        });

        qtdBanheiroInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        tipoLavabosInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preenchCampos)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelNome)
                                .addComponent(nomeObraInput, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tipoDoSobradoInput, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelTipoSobrado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(labelLaje)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelReboco))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lajeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rebocoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(alvenariaMetroInput, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelAlvenariaMetros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelObraMetros)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelVigaBaldrame)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelCobertura)
                                            .addComponent(CoberturaMLInput, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(labelTipo))))
                                    .addComponent(metroObraInput, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VigaBaldrameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTijolo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tijoloTipoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelContraPiso)
                                            .addComponent(contraPisoEmMetrosInput, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(labelBanheirosQtde)
                                            .addComponent(tipoMaterialInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(qtdBanheiroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(24, 24, 24)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataTerminoInput)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataInicioInput))
                    .addComponent(boxUmavezInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPilares)
                    .addComponent(pilaresMLInput, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEsquadria)
                    .addComponent(esquadriaMetrosInput, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLavaboQtde)
                    .addComponent(tipoLavabosInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoSalvarObra)
                .addGap(18, 18, 18)
                .addComponent(botaoCancelarObra)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preenchCampos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeObraInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataInicioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelTipoSobrado)
                    .addComponent(labelLaje)
                    .addComponent(labelReboco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataTerminoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoDoSobradoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lajeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rebocoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelObraMetros)
                    .addComponent(labelAlvenariaMetros)
                    .addComponent(boxUmavezInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metroObraInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alvenariaMetroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVigaBaldrame)
                    .addComponent(labelCobertura)
                    .addComponent(labelPilares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VigaBaldrameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CoberturaMLInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilaresMLInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTijolo)
                    .addComponent(labelTipo)
                    .addComponent(labelEsquadria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tijoloTipoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoMaterialInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esquadriaMetrosInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContraPiso)
                    .addComponent(labelBanheirosQtde)
                    .addComponent(labelLavaboQtde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraPisoEmMetrosInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtdBanheiroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoLavabosInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarObra)
                    .addComponent(botaoCancelarObra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeObraInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeObraInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeObraInputActionPerformed

    private void dataTerminoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTerminoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataTerminoInputActionPerformed

    private void dataInicioInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataInicioInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataInicioInputActionPerformed

    private void botaoSalvarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarObraActionPerformed
        try {
            preencherCampo();
        } catch (Exception ex) {
            Logger.getLogger(FormularioObrasSobrado.class.getName()).log(Level.SEVERE, null, ex);
        }
        FormularioObrasSalao.this.dispose();
        limparCampos();
        
    }//GEN-LAST:event_botaoSalvarObraActionPerformed

    private void botaoCancelarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarObraActionPerformed
       FormularioObrasSalao.this.dispose();
    }//GEN-LAST:event_botaoCancelarObraActionPerformed

    private void tipoDoSobradoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDoSobradoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDoSobradoInputActionPerformed

    private void alvenariaMetroInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alvenariaMetroInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alvenariaMetroInputActionPerformed

    private void metroObraInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metroObraInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metroObraInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioObrasSobrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioObrasSobrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioObrasSobrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioObrasSobrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioObrasSobrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CoberturaMLInput;
    private javax.swing.JTextField VigaBaldrameInput;
    private javax.swing.JTextField alvenariaMetroInput;
    private javax.swing.JButton botaoCancelarObra;
    private javax.swing.JButton botaoSalvarObra;
    private javax.swing.JComboBox boxUmavezInput;
    private javax.swing.JTextField contraPisoEmMetrosInput;
    private javax.swing.JTextField dataInicioInput;
    private javax.swing.JTextField dataTerminoInput;
    private javax.swing.JTextField esquadriaMetrosInput;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelAlvenariaMetros;
    private javax.swing.JLabel labelBanheirosQtde;
    private javax.swing.JLabel labelCobertura;
    private javax.swing.JLabel labelContraPiso;
    private javax.swing.JLabel labelEsquadria;
    private javax.swing.JLabel labelLaje;
    private javax.swing.JLabel labelLavaboQtde;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelObraMetros;
    private javax.swing.JLabel labelPilares;
    private javax.swing.JLabel labelReboco;
    private javax.swing.JLabel labelTijolo;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTipoSobrado;
    private javax.swing.JLabel labelVigaBaldrame;
    private javax.swing.JComboBox lajeInput;
    private javax.swing.JTextField metroObraInput;
    private javax.swing.JTextField nomeObraInput;
    private javax.swing.JTextField pilaresMLInput;
    private javax.swing.JLabel preenchCampos;
    private javax.swing.JComboBox qtdBanheiroInput;
    private javax.swing.JComboBox rebocoInput;
    private javax.swing.JComboBox tijoloTipoInput;
    private javax.swing.JComboBox tipoDoSobradoInput;
    private javax.swing.JComboBox tipoLavabosInput;
    private javax.swing.JComboBox tipoMaterialInput;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos(){
        if(nomeObraInput.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Digite o nome da Obra");
            nomeObraInput.requestFocus();
            return false;
        }
        return true;
    }
    public void preencherCampo() throws Exception{
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("Insert into obra (nome_obra, data_inicio, data_termino, tipo_obra, metro_quadrado_obra, altura_obra) values(?,?,?,?,?,?)");
            pst.setString(1, nomeObraInput.getText());
            pst.setString(2, dataInicioInput.getText());
            pst.setString(3, dataTerminoInput.getText());
            pst.setString(4, tipoDoSobradoInput.getName());
            pst.setDouble(5, new Double(metroObraInput.getText()));
            pst.setDouble(6, 1.0);
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(FormularioObrasSobrado.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("Insert into insumos (metroQuadAlv, metroQuadReb, metroQuadViga, metroQuadCobertura, pintura, tipoTijolo, quantEsq, quantPilar, quantBanheiro, quantCozinha)values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            pst.setDouble(1, new Double(alvenariaMetroInput.getText()));

        } catch (SQLException ex) {
            Logger.getLogger(FormularioObrasSobrado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void limparCampos(){
        nomeObraInput.setText("");
        dataInicioInput.setText("");
        dataTerminoInput.setText("");
        contraPisoEmMetrosInput.setText("");
        alvenariaMetroInput.setText("");
        metroObraInput.setText("");
        pilaresMLInput.setText("");
        esquadriaMetrosInput.setText("");
        contraPisoEmMetrosInput.setText("");
        CoberturaMLInput.setText("");
        VigaBaldrameInput.setText("");
        qtdBanheiroInput.setSelectedIndex(0);
        rebocoInput.setSelectedIndex(0);
        tijoloTipoInput.setSelectedIndex(0);
        tipoDoSobradoInput.setSelectedIndex(0);
        tipoLavabosInput.setSelectedIndex(0);
        tipoMaterialInput.setSelectedIndex(0);
        
    }
}

